/* tslint:disable */
/* eslint-disable */
/**
 * Application API
 * desc
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: test@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientPreview
 */
export interface ClientPreview {
    /**
     * 
     * @type {number}
     * @memberof ClientPreview
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientPreview
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPreview
     */
    phoneNumber?: string;
}

/**
 * Check if a given object implements the ClientPreview interface.
 */
export function instanceOfClientPreview(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ClientPreviewFromJSON(json: any): ClientPreview {
    return ClientPreviewFromJSONTyped(json, false);
}

export function ClientPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientPreview {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    };
}

export function ClientPreviewToJSON(value?: ClientPreview | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'phoneNumber': value.phoneNumber,
    };
}

